export const GET_CONTACTS_START = 'GET_CONTACTS_START';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const LOAD_SELECTED_CONTACTS_START = 'LOAD_SELECTED_CONTACTS_START';
export const LOAD_SELECTED_CONTACTS_SUCCESS = 'LOAD_SELECTED_CONTACTS_SUCCESS';
export const LOAD_SELECTED_CONTACTS_FAIL = 'LOAD_SELECTED_CONTACTS_FAIL';

export const SAVE_SELECTED_CONTACTS_START = 'SAVE_SELECTED_CONTACTS_START';
export const SAVE_SELECTED_CONTACTS_SUCCESS = 'SAVE_SELECTED_CONTACTS_SUCCESS';
export const SAVE_SELECTED_CONTACTS_FAIL = 'SAVE_SELECTED_CONTACTS_FAIL';
